# Generated by Django 5.2.3 on 2025-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
