# Generated by Django 5.2.3 on 2025-07-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_mpesa_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_seen',
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
