# Generated by Django 5.2.3 on 2025-07-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_admin_seen_order_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
